name: Build ISO
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Tools and Build
        run: |
          # 1. Install the tools needed to understand Arch Linux scripts
          sudo apt update
          sudo apt install -y arch-install-scripts mkisofs squashfs-tools

          # 2. Give the robot permission to read your folder
          chmod -R 777 .

          # 3. Run your specific build script
          cd Archiv && sudo ./create-arch-iso.sh
          
      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: DobermanOS-Arch-ISO
          path: Archiv/*.iso
